export const VISITING_PLACES_REQUEST = "VISITING_PLACES_REQUEST";
export const VISITING_PLACES_REQUEST_SUCCESS =
  "VISITING_PLACES_REQUEST_SUCCESS";
export const VISITING_PLACES_REQUEST_FAILURE =
  "VISITING_PLACES_REQUEST_FAILURE";

export const FAVOURITE_PLACES_COUNT_REQUEST_SUCCESS =
  "FAVOURITE_PLACES_COUNT_REQUEST_SUCCESS";
